from pyexpat import model
from openai import OpenAI


# Import the necessary libraries


# Call the language model API to get the response

def ask_language_model(question, engine, api_key) -> str:
    """
    Calls the language model API to get a response for the given question.

    Args:
        question (str): The question to ask the language model.
        engine (str): The name of the language model engine to use.
        api_key (str): The API key for accessing the language model API.

    Returns:
        str: The response generated by the language model.
    """
    # Call the language model API to get the response
    client = OpenAI(api_key=api_key)
    response = client.completions.create(
        model=engine,
        prompt=question,
        max_tokens=100,
        temperature=0.7)
    # Return the response from the language model
    return response.choices[0].text.strip()
